development:
  adapter: postgresql
  database: learntrace_development
  username: postgres
  host: localhost
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: learntrace_test
  username: postgres
  host: localhost
  encoding: utf8
  pool: 5

cucumber:
  <<: *test
